version: "1.0"
info:
  model: int-scaffold
packages:
- name: WmJDBCAdapter
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
- name: FR_STT_TemplateProject
  gitServerName: staillanibm
  gitUrl: https://github.com/staillanibm
  gitUsername: staillanibm
  gitBranch: main
services:
- serviceName: project.fr_stt_template.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:dbcon_template
  packages:
  - name: FR_STT_TemplateProject
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
configurationVariables:
  ? artConnection.FR_STT_TemplateProject.project.fr_stt_template.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbcon_template.connectionSettings.keyStore
  : ""
  ? artConnection.FR_STT_TemplateProject.project.fr_stt_template.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbcon_template.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.FR_STT_TemplateProject.project.fr_stt_template.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbcon_template.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.FR_STT_TemplateProject.project.fr_stt_template.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbcon_template.connectionSettings.serverName
  : contabo.sttlab.eu
  ? artConnection.FR_STT_TemplateProject.project.fr_stt_template.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbcon_template.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.FR_STT_TemplateProject.project.fr_stt_template.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbcon_template.connectionSettings.otherProperties
  : loginTimeout=60;
  ? artConnection.FR_STT_TemplateProject.project.fr_stt_template.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbcon_template.connectionSettings.networkProtocol
  : ""
  ? artConnection.FR_STT_TemplateProject.project.fr_stt_template.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbcon_template.connectionSettings.user
  : sa
  ? artConnection.FR_STT_TemplateProject.project.fr_stt_template.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbcon_template.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.sqlserver.SQLServerDataSource
  ? artConnection.FR_STT_TemplateProject.project.fr_stt_template.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbcon_template.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.FR_STT_TemplateProject.project.fr_stt_template.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbcon_template.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.FR_STT_TemplateProject.project.fr_stt_template.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbcon_template.connectionSettings.trustStore
  : ""
  ? artConnection.FR_STT_TemplateProject.project.fr_stt_template.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbcon_template.connectionSettings.dbType
  : MSSQL
  ? artConnection.FR_STT_TemplateProject.project.fr_stt_template.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbcon_template.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.FR_STT_TemplateProject.project.fr_stt_template.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbcon_template.connectionSettings.databaseName
  : sandbox
  ? artConnection.FR_STT_TemplateProject.project.fr_stt_template.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbcon_template.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.FR_STT_TemplateProject.project.fr_stt_template.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbcon_template.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.FR_STT_TemplateProject.project.fr_stt_template.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbcon_template.connectionManagerSettings.poolable
  : "true"
  ? artConnection.FR_STT_TemplateProject.project.fr_stt_template.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbcon_template.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.FR_STT_TemplateProject.project.fr_stt_template.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbcon_template.connectionEnabled
  : "false"
  ? artConnection.FR_STT_TemplateProject.project.fr_stt_template.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbcon_template.connectionSettings.password
  : "{AES}zxtjDVPnPMSWIVvNbTQB+H9awpHAyfXYCxLWEZQhnoE="
  ? artConnection.FR_STT_TemplateProject.project.fr_stt_template.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbcon_template.connectionSettings.driverType
  : Progress® DataDirect®
  ? artConnection.FR_STT_TemplateProject.project.fr_stt_template.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.dbcon_template.connectionSettings.portNumber
  : "1433"
